Update patch set 1
Patch Set 1: Verified-1

This is an automated message from the Deckard Autoverifier.

Patchset merges but does not build in AOSP.
The following snippet of `make` output may point you in the right direction:

  packages/apps/Settings/src/com/android/settings/wifi/WpsDialog.java:187: error: incompatible types
        mWpsListenerKey = mWifiManager.startWps(wpsConfig, mWpsListener);
                                               ^
  required: int
  found:    void
packages/apps/Settings/src/com/android/settings/wifi/WpsDialog.java:194: error: method cancelWps in class WifiManager cannot be applied to given types;
            mWifiManager.cancelWps(mWpsListenerKey);
                        ^
  required: ActionListener
...


If your patchset has a dependency in a separate project, please ensure that
both changes are uploaded with the same Change-Id.

Patch-set: 1
Reviewer: Deckard Autoverifier <1006433@85c56323-6fa9-3386-8a01-6480fb634889>
Label: Verified=-1