Update patch set 2
Patch Set 2: Verified-1

This is an automated message from the Deckard Autoverifier.

Patchset merges but does not build in AOSP.
The following snippet of `make` output may point you in the right direction:

  packages/apps/Settings/src/com/android/settings/siminfo/SubscriptionSettingUtility.java:10: cannot find symbol
symbol  : class SubscriptionController
location: package android.telephony
import android.telephony.SubscriptionController;
                        ^
packages/apps/Settings/src/com/android/settings/siminfo/SubscriptionSettingUtility.java:11: package android.telephony.SubscriptionController does not exist
import android.telephony.SubscriptionController.SubInfoRecord;
                                               ^
packages/apps/Settings/src/com/android/settings/DataUsageSummary.java:92: cannot find symbol
...


If your patchset has a dependency in a separate project, please ensure that
both changes are uploaded with the same Change-Id.

Patch-set: 2
Label: Verified=-1