Update patch set 1
Patch Set 1: Fails

This is an automated message from the Deckard Autoverifier:

This patchset fails to build in the public AOSP source tree.  The following snippet of output from `make` may point you in the right direction:

packages/apps/Settings/src/com/android/settings/SoundSettings.java:264: cannot find symbol
symbol  : variable VOLUME_OVERLAY_SINGLE
location: class android.provider.Settings.System
                toPersist = Settings.System.VOLUME_OVERLAY_SINGLE;
                                           ^
packages/apps/Settings/src/com/android/settings/SoundSettings.java:266: cannot find symbol
symbol  : variable VOLUME_OVERLAY_EXPANDABLE
location: class android.provider.Settings.System
                toPersist = Settings.System.VOLUME_OVERLAY_EXPANDABLE;
                                           ^

If your patchset has a dependency in a separate project and you believe that this is the cause of the breakage, a reviewer can verify +1 and Deckard will remove the verify -1 shortly thereafter.

Otherwise, if you wish to pursue this change, please fix the error and upload a new patchset.

Thanks!

Patch-set: 1