Update patch set 5
Patch Set 5:

Would you help to check these presubmit errors?
Thank you.

packages/apps/Settings/tests/robotests/src/com/android/settings/wifi/tether/WifiTetherSwitchBarControllerTest.java:73: error: constructor WifiTetherSwitchBarController in class WifiTetherSwitchBarController cannot be applied to given types;
mController = new WifiTetherSwitchBarController(mContext,
^
required: Context,SwitchBar
found: Context,SwitchBarController
reason: argument mismatch; SwitchBarController cannot be converted to SwitchBar
packages/apps/Settings/tests/robotests/src/com/android/settings/wifi/tether/WifiTetherSwitchBarControllerTest.java:106: error: cannot find symbol
mController.onSwitchToggled(true);
^
symbol: method onSwitchToggled(boolean)
location: variable mController of type WifiTetherSwitchBarController
packages/apps/Settings/tests/robotests/src/com/android/settings/wifi/tether/WifiTetherSwitchBarControllerTest.java:111: error: cannot find symbol
mController.onSwitchToggled(true);
^
symbol: method onSwitchToggled(boolean)
location: variable mController of type WifiTetherSwitchBarController
3 errors

Patch-set: 5
Reviewer: Gerrit User 1356080 <1356080@85c56323-6fa9-3386-8a01-6480fb634889>