Disable R8 for Settings
This failure seems related to R8:

https://sponge.corp.google.com/target?show=FAILED&sortBy=STATUS&id=4f1b303e-ef57-4dc6-9ebb-95ca5cda398e&target=com.android.settings.tests.unit:

java.lang.InstantiationError: com.android.settings.bluetooth.Utf8ByteLengthFilter
at com.android.settings.bluetooth.Utf8ByteLengthFilterTest.testFilter(Utf8ByteLengthFilterTest.java:34)
at java.lang.reflect.Method.invoke(Native Method)
at junit.framework.TestCase.runTest(TestCase.java:168)
at junit.framework.TestCase.runBare(TestCase.java:134)
at junit.framework.TestResult$1.protect(TestResult.java:115)
at android.support.test.internal.runner.junit3.AndroidTestResult.runProtected(AndroidTestResult.java:73)
at junit.framework.TestResult.run(TestResult.java:118)
at android.support.test.internal.runner.junit3.AndroidTestResult.run(AndroidTestResult.java:51)
at junit.framework.TestCase.run(TestCase.java:124)
at android.support.test.internal.runner.junit3.NonLeakyTestSuite$NonLeakyTest.run(NonLeakyTestSuite.java:62)
at android.support.test.internal.runner.junit3.AndroidTestSuite$2.run(AndroidTestSuite.java:101)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:764)

Bug: 74756073
Test: Run Settings tests, and the failure above is gone.

(cherry picked from commit f416cf775e5adf76c4f45f1471b7a25e9aeae906)

Change-Id: I7aa269250598071c150575c4385e555f18c72721
Merged-In: I6071ae59f51ab5d56243774855ecc845267e7103