Ignore onRemove callback to detached fragment
1. Set up five fingerprints
2. Delete two fingerprints after eachother
3. Try to delete the same fingerprint as you just erased
4. Go back to home by pressing 'back' several times.
-> Settings crashes

Crash signature:
java.lang.NullPointerException: Attempt to invoke virtual method 'andro\
id.content.res.Resources android.content.Context.getResources()' on a n\
ull object reference
at com.android.settings.fingerprint.FingerprintSettings$FingerprintSett\
ingsFragment.updateAddPreference(FingerprintSettings.java:374)
at com.android.settings.fingerprint.FingerprintSettings$FingerprintSett\
ingsFragment.-wrap4(FingerprintSettings.java)
at com.android.settings.fingerprint.FingerprintSettings$FingerprintSett\
ingsFragment$3.handleMessage(FingerprintSettings.java:212)

This crash may be difficult to reproduce and depends on thread
scheduling and version of the fingerprint hal. The fix is basically the
same as 622142c.

Issue: CH-5239
Change-Id: Iabcb963a9c243d00fb0fe34f5e79b36a497af5c3