Update patch set 1
Patch Set 1: Fails

This is an automated message from the Deckard Autoverifier:

This patchset fails to build in the public AOSP source tree.  The following snippet of output from `make` may point you in the right direction:

packages/apps/Settings/src/com/android/settings/SoundSettings.java:165: cannot find symbol
symbol  : variable VOLUME_ADJUST_SOUNDS_ENABLED
location: class android.provider.Settings.System
            Settings.System.VOLUME_ADJUST_SOUNDS_ENABLED, 1) != 0);
                           ^
packages/apps/Settings/src/com/android/settings/SoundSettings.java:341: cannot find symbol
symbol  : variable VOLUME_ADJUST_SOUNDS_ENABLED
location: class android.provider.Settings.System
            Settings.System.putInt(getContentResolver(), Settings.System.VOLUME_ADJUST_SOUNDS_ENABLED , mVolumeAdjustSounds.isChecked() ? 1 : 0);
                                                                        ^

If your patchset has a dependency in a separate project and you believe that this is the cause of the breakage, a reviewer can verify +1 and Deckard will remove the verify -1 shortly thereafter.

Otherwise, if you wish to pursue this change, please fix the error and upload a new patchset.

Thanks!

Patch-set: 1