Update patch set 2
Patch Set 2: Fails

This is an automated message from the Deckard Autoverifier:

This patchset fails to build in the public AOSP source tree.  The following snippet of output from `make` may point you in the right direction:

packages/apps/Settings/src/com/android/settings/DeviceInfoSettings.java:34: cannot find symbol
symbol  : class SELinux
location: package android.os
import android.os.SELinux;
                 ^
packages/apps/Settings/src/com/android/settings/DeviceInfoSettings.java:80: cannot find symbol
symbol  : variable SELinux
location: class com.android.settings.DeviceInfoSettings
        if (!SELinux.isSELinuxEnabled()) {
             ^

If your patchset has a dependency in a separate project and you believe that this is the cause of the breakage, a reviewer can verify +1 and Deckard will remove the verify -1 shortly thereafter.

Otherwise, if you wish to pursue this change, please fix the error and upload a new patchset.

Thanks!

Patch-set: 2
Reviewer: Deckard Autoverifier <1006433@85c56323-6fa9-3386-8a01-6480fb634889>
Label: Code-Review=0
Label: Verified=-1